// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1LzWmL9H4z1r4SyBewiLyzWbEvBjVBtw',
    appId: '1:445254650043:web:27348096a548fe5468819e',
    messagingSenderId: '445254650043',
    projectId: 'sumgo-crawller-flutter',
    authDomain: 'sumgo-crawller-flutter.firebaseapp.com',
    storageBucket: 'sumgo-crawller-flutter.appspot.com',
    measurementId: 'G-WW9Y5CJB34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAByrmf7bEBPFMLU970Kg-n_RTBxigYUwk',
    appId: '1:445254650043:android:343b87789b63669568819e',
    messagingSenderId: '445254650043',
    projectId: 'sumgo-crawller-flutter',
    storageBucket: 'sumgo-crawller-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU9pPmikregUgvo7ZVzP3Tb7CgIhh8aew',
    appId: '1:445254650043:ios:f03fe34f25e4408568819e',
    messagingSenderId: '445254650043',
    projectId: 'sumgo-crawller-flutter',
    storageBucket: 'sumgo-crawller-flutter.appspot.com',
    iosClientId: '445254650043-l1bn5f5603b6be7lkh8uf79dh3mc5vuv.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
